version: "3"
services:
#next-cloud
  nextcloud:
    container_name: nextcloud
    restart: unless-stopped
    image: nextcloud
    ports:
      - "8080:80"
    volumes:
      - /mnt/WDBlack/nextcloud/apps:/var/www/html/apps
      - /mnt/WDBlack/nextcloud/config:/var/www/html/config
      - /mnt/WDBlack/nextcloud/data:/var/www/html/data
    depends_on:
      - nextcloud_db
  nextcloud_db:
    container_name: maria-db
    restart: unless-stopped
    image: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    volumes:
      - /containers/cloud/mariadb:/var/lib/mysql
#nginx-proxy
  nginix-proxy:
    container_name: nginix-proxy
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - "82:80"
      - "81:81"
      - "443:443"
    volumes:
      - /docker/nginix-proxy/config.json:/app/config/production.json
      - /docker/nginix-proxy/data:/data
      - /docker/nginix-proxy/letsencrypt:/etc/letsencrypt
  db_nginx:
    image: 'yobasystems/alpine-mariadb:latest'
    container_name: nginix-proxy_db
    environment:
      MYSQL_ROOT_PASSWORD: ${NGINX_DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${NGINX_DB_MYSQL_DATABASE}
      MYSQL_USER: ${NGINX_DB_MYSQL_USER}
      MYSQL_PASSWORD: ${NGINX_DB_MYSQL_PASSWORD}
    volumes:
      - /docker/nginix-proxy/data/mysql:/var/lib/mysql
    restart: always
#heimdall
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
    volumes:
      - /containers/heimdall/config:/config
    ports:
      - "8888:80"
      - "9443:443"
    restart: unless-stopped
#Plex
  plex:
    image: lscr.io/linuxserver/plex:latest
    container_name: plex
    network_mode: host
    ports:
      - "32400:32400"
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - VERSION=docker
      - PLEX_CLAIM= #optional
    volumes:
      - /mnt/Toshiba:/config
      - /mnt/Toshiba/Torrent/Pobrane:/tv
      - /mnt/Toshiba/Torrent/Pobrane:/movies
    restart: unless-stopped
#Pi-hole
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "8000:80/tcp"
    environment:
      TZ: 'Europe/Prague'
      WEBPASSWORD: ${PIHOLE_WEB_PASSWORD}
    volumes:
      - '/docker/pihole/etc-pihole:/etc/pihole'
      - '/docker/pihole:/etc/dnsmasq.d'
    cap_add:
      - NET_ADMIN
    restart: always
#qbittorrent
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - WEBUI_PORT=8080
    volumes:
      - /containers/qbittorrent/appdata/config:/config
      - /mnt/Toshiba/Torrent/downloads:/downloads
      - /mnt/Toshiba/Torrent/Pobrane:/Pobrane
      - /mnt/Toshiba/Torrent/.autoadd:/.autoadd
    ports:
      - 27015:8080
      - 6881:6881
      - 6881:6881/udp
      - 49152:49152
      - 49152:49152/udp
